### ISSUE TITLE
Narrow down languages to be used

### ISSUE THREAD

**Issue by pxlpnk** [esumbar/passphrase#3]
The general idea of using a diceware based passphrase is to be able to remember it in an easy way. As much as I love the idea of using different languages it makes it sometimes quite hard to remember the words as one can have a hard time building up an association with it.

I think it could make sense to either selectively include languages or exclude a language. 
What do you think?

**Comment by esumbar** [comment]
I actually did think about the approach you mention. As I mentioned in the README however, I decided to take advantage of the increased security at the expense of loss of familiarity. Besides, I wanted to keep the interface as simple as possible.

At one time, I even considered automatically selecting the language based on the user's locale (defaulting to English if the wordlist didn't include an appropriate language), but I couldn't find an easy, portable method of determining locale in Ruby. To be honest, I didn't try very hard.

In my experience, I found that a new passphrase of four or five random words is not easy to remember, even if the words are recognizable, and particularly when I have many different passphrases in use. I admit that I've never bothered to come up with associations to help me remember. I think you'd need to be quite creative to be good at that sort of thing. Not everyone has that talent. I certainly don't.

Instead, what I've always relied on is muscle memory. As time passes, as I use a passphrase more, my fingers (not my mind) learn the passphrase... sort of like touch typing. Naturally, I keep the passphrase written down on a piece of paper until my fingers have had enough training.
